import { Show } from './types';

type Program = Omit<Show, 'days'>;

// ---------------------------------------------------------------------------
// Imagens dos programas (Cloudinary)
// ---------------------------------------------------------------------------
export const PROGRAM_IMAGES = {
  nightShift: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831666/the-night-shift_hpgryk.webp',
  worship: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831668/worship_q6dsql.webp',
  aussieMorning: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831666/aussie-morning_wo7qjl.webp',
  middayJourney: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831666/midday-journey_iebims.webp',
  ozHipHop: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831668/oz-hiphop_pdhxqt.webp',
  nextWave: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831667/next-wave_zsxmpi.webp',
  roadToHome: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831668/road-to-home_rjgcr9.webp',
  faithFuzzy: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831666/faith-fuzzy_vy0wii.webp',
  throwback: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831668/throwback_ypql0b.webp',
  atmosphereChill: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831666/atmos-chill_u0ay2q.webp',
  roadToChurch: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831668/road-to-church_ab0zkf.webp',
  sundayService: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781832959/sunday-service_s46wns.webp',
};

// ---------------------------------------------------------------------------
// Segunda a Sábado
// ---------------------------------------------------------------------------
const WEEKDAY_SCHEDULE: Program[] = [
  {
    id: 'wd-night-shift',
    title: 'The Night Shift',
    host: 'Noah Bennett',
    startTime: '00:00',
    endTime: '06:00',
    image: PROGRAM_IMAGES.nightShift,
    description: 'Your company through the late-night.',
  },
  {
    id: 'wd-worship-1',
    title: 'Worship',
    host: 'Praise FM',
    startTime: '06:00',
    endTime: '07:00',
    image: PROGRAM_IMAGES.worship,
    description: 'A peaceful hour of worship music to start your day with the right heart.',
  },
  {
    id: 'wd-aussie-morning',
    title: 'Aussie Morning',
    host: 'Olivia Blake',
    startTime: '07:00',
    endTime: '12:00',
    image: PROGRAM_IMAGES.aussieMorning,
    description: 'Your morning companion with news, music, and good energy to kick off the day.',
  },
  {
    id: 'wd-worship-2',
    title: 'Worship',
    host: 'Praise FM',
    startTime: '12:00',
    endTime: '13:00',
    image: PROGRAM_IMAGES.worship,
    description: 'A midday pause for worship and reflection.',
  },
  {
    id: 'wd-midday-journey',
    title: 'Midday Journey',
    host: 'Kelly Fergusson',
    startTime: '13:00',
    endTime: '16:00',
    image: PROGRAM_IMAGES.middayJourney,
    description: 'An afternoon journey through great music and uplifting conversation.',
  },
  {
    id: 'wd-oz-hiphop',
    title: 'Oz Hip Hop',
    host: 'DJ Jarrah',
    startTime: '16:00',
    endTime: '17:00',
    image: PROGRAM_IMAGES.ozHipHop,
    description: 'The best of Australian hip hop.',
  },
  {
    id: 'wd-next-wave',
    title: 'Next Wave',
    host: 'Sophie Mitchell',
    startTime: '17:00',
    endTime: '18:00',
    image: PROGRAM_IMAGES.nextWave,
    description: 'New releases and rising artists.',
  },
  {
    id: 'wd-road-to-home',
    title: 'Road To Home',
    host: 'Emily Davis',
    startTime: '18:00',
    endTime: '20:00',
    image: PROGRAM_IMAGES.roadToHome,
    description: 'Your drive-time soundtrack for the trip back home.',
  },
  {
    id: 'wd-faith-fuzzy',
    title: 'Faith & Fuzzy',
    host: 'Jezza',
    startTime: '20:00',
    endTime: '21:00',
    image: PROGRAM_IMAGES.faithFuzzy,
    description: 'A warm, easygoing hour blending faith talk with feel-good tunes.',
  },
  {
    id: 'wd-throwback',
    title: 'Throwback',
    host: 'Jack Thompson',
    startTime: '21:00',
    endTime: '22:00',
    image: PROGRAM_IMAGES.throwback,
    description: 'Classic hits and nostalgic favourites from years gone by.',
  },
  {
    id: 'wd-atmosphere-chill',
    title: 'Atmosphere Chill',
    host: 'Thy Keller',
    startTime: '22:00',
    endTime: '00:00',
    image: PROGRAM_IMAGES.atmosphereChill,
    description: 'Mellow, atmospheric sounds to wind down before bed.',
  },
];

// ---------------------------------------------------------------------------
// Domingo
// ---------------------------------------------------------------------------
const SUNDAY_SCHEDULE: Program[] = [
  {
    id: 'sun-night-shift',
    title: 'The Night Shift',
    host: 'Noah Bennett',
    startTime: '00:00',
    endTime: '06:00',
    image: PROGRAM_IMAGES.nightShift,
    description: 'Smooth tracks and late-night vibes to keep you company through the early hours.',
  },
  {
    id: 'sun-worship-1',
    title: 'Worship',
    host: 'Praise FM',
    startTime: '06:00',
    endTime: '07:00',
    image: PROGRAM_IMAGES.worship,
    description: 'A peaceful hour of worship music to start your Sunday with the right heart.',
  },
  {
    id: 'sun-road-to-church',
    title: 'Road to Church',
    host: 'Matthew Reed',
    startTime: '07:00',
    endTime: '12:00',
    image: PROGRAM_IMAGES.roadToChurch,
    description: 'Get ready for church with uplifting music and a Sunday morning lift.',
  },
  {
    id: 'sun-worship-2',
    title: 'Worship',
    host: 'Praise FM',
    startTime: '12:00',
    endTime: '13:00',
    image: PROGRAM_IMAGES.worship,
    description: 'A midday pause for worship and reflection.',
  },
  {
    id: 'sun-midday-journey',
    title: 'Midday Journey',
    host: 'Kelly Fergusson',
    startTime: '13:00',
    endTime: '16:00',
    image: PROGRAM_IMAGES.middayJourney,
    description: 'An afternoon journey through great music and uplifting conversation.',
  },
  {
    id: 'sun-oz-hiphop',
    title: 'Oz Hip Hop',
    host: 'DJ Jarrah',
    startTime: '16:00',
    endTime: '17:00',
    image: PROGRAM_IMAGES.ozHipHop,
    description: 'The best of Australian hip hop, fresh beats and homegrown talent.',
  },
  {
    id: 'sun-next-wave',
    title: 'Next Wave',
    host: 'Sophie Mitchell',
    startTime: '17:00',
    endTime: '18:00',
    image: PROGRAM_IMAGES.nextWave,
    description: 'New releases and rising artists you need to hear next.',
  },
  {
    id: 'sun-worship-3',
    title: 'Worship',
    host: 'Praise FM',
    startTime: '18:00',
    endTime: '20:00',
    image: PROGRAM_IMAGES.worship,
    description: 'An evening of worship music to close out the weekend.',
  },
  {
    id: 'sun-service-1',
    title: 'Sunday Service',
    host: 'Praise FM',
    startTime: '20:00',
    endTime: '21:00',
    image: PROGRAM_IMAGES.sundayService,
    description: 'Join the Sunday Service.',
  },
  {
    id: 'sun-throwback',
    title: 'Throwback',
    host: 'Jack Thompson',
    startTime: '21:00',
    endTime: '22:00',
    image: PROGRAM_IMAGES.throwback,
    description: 'Classic hits.',
  },
  {
    id: 'sun-atmosphere-chill',
    title: 'Atmosphere Chill',
    host: 'Thy Keller',
    startTime: '22:00',
    endTime: '00:00',
    image: PROGRAM_IMAGES.atmosphereChill,
    description: 'Mellow, atmospheric sounds to wind down before bed.',
  },
];

// ---------------------------------------------------------------------------
// Mapa final usado pelo ScheduleList (0 = Domingo ... 6 = Sábado)
// ---------------------------------------------------------------------------
export const SCHEDULES: { [key: number]: Program[] } = {
  0: SUNDAY_SCHEDULE,
  1: WEEKDAY_SCHEDULE,
  2: WEEKDAY_SCHEDULE,
  3: WEEKDAY_SCHEDULE,
  4: WEEKDAY_SCHEDULE,
  5: WEEKDAY_SCHEDULE,
  6: WEEKDAY_SCHEDULE,
};

// ---------------------------------------------------------------------------
// SHOWS — lista plana usada por getCurrentShow() (cada show sabe em quais
// dias toca, via `days`: 0 = Domingo ... 6 = Sábado)
// ---------------------------------------------------------------------------
export const SHOWS: Show[] = [
  {
    id: 'night-shift',
    title: 'The Night Shift',
    host: 'Noah Bennett',
    startTime: '00:00',
    endTime: '06:00',
    image: PROGRAM_IMAGES.nightShift,
    description: 'Smooth tracks and late-night vibes to keep you company through the early hours.',
    days: [0, 1, 2, 3, 4, 5, 6],
  },
  {
    id: 'worship-morning',
    title: 'Worship',
    host: 'Praise FM',
    startTime: '06:00',
    endTime: '07:00',
    image: PROGRAM_IMAGES.worship,
    description: 'A peaceful hour of worship music to start your day with the right heart.',
    days: [0, 1, 2, 3, 4, 5, 6],
  },
  {
    id: 'aussie-morning',
    title: 'Aussie Morning',
    host: 'Olivia Blake',
    startTime: '07:00',
    endTime: '12:00',
    image: PROGRAM_IMAGES.aussieMorning,
    description: 'Your morning companion with news, music, and good energy to kick off the day.',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 'road-to-church',
    title: 'Road to Church',
    host: 'Matthew Reed',
    startTime: '07:00',
    endTime: '12:00',
    image: PROGRAM_IMAGES.roadToChurch,
    description: 'Get ready for church with uplifting music and a Sunday morning lift.',
    days: [0],
  },
  {
    id: 'worship-midday',
    title: 'Worship',
    host: 'Praise FM',
    startTime: '12:00',
    endTime: '13:00',
    image: PROGRAM_IMAGES.worship,
    description: 'A midday pause for worship and reflection.',
    days: [0, 1, 2, 3, 4, 5, 6],
  },
  {
    id: 'midday-journey',
    title: 'Midday Journey',
    host: 'Kelly Fergusson',
    startTime: '13:00',
    endTime: '16:00',
    image: PROGRAM_IMAGES.middayJourney,
    description: 'An afternoon journey through great music and uplifting conversation.',
    days: [0, 1, 2, 3, 4, 5, 6],
  },
  {
    id: 'oz-hiphop',
    title: 'Oz Hip Hop',
    host: 'DJ Jarrah',
    startTime: '16:00',
    endTime: '17:00',
    image: PROGRAM_IMAGES.ozHipHop,
    description: 'The best of Australian hip hop, fresh beats and homegrown talent.',
    days: [0, 1, 2, 3, 4, 5, 6],
  },
  {
    id: 'next-wave',
    title: 'Next Wave',
    host: 'Sophie Mitchell',
    startTime: '17:00',
    endTime: '18:00',
    image: PROGRAM_IMAGES.nextWave,
    description: 'New releases and rising artists you need to hear next.',
    days: [0, 1, 2, 3, 4, 5, 6],
  },
  {
    id: 'road-to-home',
    title: 'Road To Home',
    host: 'Emily Davis',
    startTime: '18:00',
    endTime: '20:00',
    image: PROGRAM_IMAGES.roadToHome,
    description: 'Your drive-time soundtrack for the trip back home.',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 'worship-evening',
    title: 'Worship',
    host: 'Praise FM',
    startTime: '18:00',
    endTime: '20:00',
    image: PROGRAM_IMAGES.worship,
    description: 'An evening of worship music to close out the weekend.',
    days: [0],
  },
  {
    id: 'faith-fuzzy',
    title: 'Faith & Fuzzy',
    host: 'Jezza',
    startTime: '20:00',
    endTime: '21:00',
    image: PROGRAM_IMAGES.faithFuzzy,
    description: 'A warm, easygoing hour blending faith talk with feel-good tunes.',
    days: [1, 2, 3, 4, 5, 6],
  },

  {
    id: 'throwback',
    title: 'Throwback',
    host: 'Jack Thompson',
    startTime: '21:00',
    endTime: '22:00',
    image: PROGRAM_IMAGES.throwback,
    description: 'Classic hits and nostalgic favourites from years gone by.',
    days: [0, 1, 2, 3, 4, 5, 6],
  },
  {
    id: 'atmosphere-chill-weekday',
    title: 'Atmosphere Chill',
    host: 'Thy Keller',
    startTime: '22:00',
    endTime: '00:00',
    image: PROGRAM_IMAGES.atmosphereChill,
    description: 'Mellow, atmospheric sounds to wind down before bed.',
    days: [1, 2, 3, 4, 5, 6],
  }
];
