import { Program, Show } from './types';

export const COLORS = {
  ACCENT: '#ff6600',
  DARK: '#1a1a1a',
  GRAY: '#f3f4f6',
};

export const SHOWS: Show[] = [
  {
    id: 1,
    title: 'The Night Shift',
    host: 'Noah Bennett',
    description: 'Late-night worship music.',
    startTime: '00:00',
    endTime: '06:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831666/the-night-shift_hpgryk.webp',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 2,
    title: 'Worship',
    host: 'Team',
    description: 'Worship Music.',
    startTime: '06:00',
    endTime: '07:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831668/worship_q6dsql.webp',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 3,
    title: 'Aussie Morning',
    host: 'Olivia Blake',
    description: 'Start your day with great music.',
    startTime: '07:00',
    endTime: '12:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831666/aussie-morning_wo7qjl.webp',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 4,
    title: 'Worship',
    host: 'Team',
    description: 'Worship Music.',
    startTime: '12:00',
    endTime: '13:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831668/worship_q6dsql.webp',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 5,
    title: 'Midday Journey',
    host: 'Kelly Fergusson',
    description: 'The soundtrack for your afternoon.',
    startTime: '13:00',
    endTime: '16:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831666/midday-journey_iebims.webp',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 6,
    title: 'Oz Hip Hop',
    host: 'DJ Jarrah',
    description: 'Christian hip hop, urban worship and beats.',
    startTime: '16:00',
    endTime: '17:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831668/oz-hiphop_pdhxqt.webp',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 7,
    title: 'Next Wave',
    host: 'Sophie Mitchell',
    description: 'Discover the next generation of Christian artists.',
    startTime: '17:00',
    endTime: '18:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831667/next-wave_zsxmpi.webp',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 8,
    title: 'Road To Home',
    host: 'Emily Davis',
    description: 'The best music to accompany your drive home.',
    startTime: '18:00',
    endTime: '20:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831668/road-to-home_rjgcr9.webp',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 9,
    title: 'Faith & Fuzzy',
    host: 'Jezza',
    description: 'Christian rock, alternative sounds anthems.',
    startTime: '20:00',
    endTime: '21:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831666/faith-fuzzy_vy0wii.webp',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 10,
    title: 'Throwback',
    host: 'Jack Thompson',
    description: 'Classic Christian hits, timeless worship.',
    startTime: '21:00',
    endTime: '22:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831668/throwback_ypql0b.webp',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 11,
    title: 'Atmosphere Chill',
    host: 'Thy Keller',
    description: 'Relaxed worship musics for the evening.',
    startTime: '22:00',
    endTime: '00:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831666/atmos-chill_u0ay2q.webp',
    days: [1, 2, 3, 4, 5, 6],
  },

  // Sunday
  {
    id: 12,
    title: 'The Night Shift',
    host: 'Noah Bennett',
    description: 'Late-night worship and music through the early hours.',
    startTime: '00:00',
    endTime: '06:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831666/the-night-shift_hpgryk.webp',
    days: [0],
  },
  {
    id: 13,
    title: 'Worship',
    host: 'Team',
    description: 'Worship Music.',
    startTime: '06:00',
    endTime: '07:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831668/worship_q6dsql.webp',
    days: [0],
  },
  {
    id: 14,
    title: 'Road To Church',
    host: 'Matthew Reed',
    description: 'Preparing your heart for worship and Sunday Service.',
    startTime: '07:00',
    endTime: '12:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831668/road-to-church_ab0zkf.webp',
    days: [0],
  },
  {
    id: 15,
    title: 'Worship',
    host: 'Team',
    description: 'Worship Music.',
    startTime: '12:00',
    endTime: '13:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831668/worship_q6dsql.webp',
    days: [0],
  },
  {
    id: 16,
    title: 'Midday Journey',
    host: 'Kelly Fergusson',
    description: 'The perfect soundtrack for your afternoon journey.',
    startTime: '13:00',
    endTime: '16:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831666/midday-journey_iebims.webp',
    days: [0],
  },
  {
    id: 17,
    title: 'Oz Hip Hop',
    host: 'DJ Jarrah',
    description: 'Christian hip hop, urban worship beats.',
    startTime: '16:00',
    endTime: '17:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831668/oz-hiphop_pdhxqt.webp',
    days: [0],
  },
  {
    id: 18,
    title: 'Next Wave',
    host: 'Sophie Mitchell',
    description: 'Discover the next generation of Christian artists.',
    startTime: '17:00',
    endTime: '18:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831667/next-wave_zsxmpi.webp',
    days: [0],
  },
  {
    id: 19,
    title: 'Worship',
    host: 'Team',
    description: 'Worship Music.',
    startTime: '18:00',
    endTime: '20:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831668/worship_q6dsql.webp',
    days: [0],
  },
  {
    id: 20,
    title: 'Sunday Service',
    host: 'Pastors',
    description: 'Biblical and worship for your Sunday.',
    startTime: '20:00',
    endTime: '21:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781832959/sunday-service_s46wns.webp',
    days: [0],
  },
  {
    id: 21,
    title: 'Throwback',
    host: 'Jack Thompson',
    description: 'Classic Christian hits and timeless worship.',
    startTime: '21:00',
    endTime: '22:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831668/throwback_ypql0b.webp',
    days: [0],
  },
  {
    id: 22,
    title: 'Atmosphere Chill',
    host: 'Thy Keller',
    description: 'Relaxed worship musics for the evening.',
    startTime: '22:00',
    endTime: '00:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1781831666/atmos-chill_u0ay2q.webp',
    days: [0],
  },
];

export const SCHEDULES: Record<number, Program[]> = {
  0: [],
  1: [],
  2: [],
  3: [],
  4: [],
  5: [],
  6: [],
};

for (let day = 0; day <= 6; day++) {
  SCHEDULES[day] = SHOWS
    .filter((show) => show.days.includes(day))
    .map((show) => ({
      id: show.id.toString(),
      title: show.title,
      host: show.host,
      startTime: show.startTime,
      endTime: show.endTime,
      description: show.description,
      image: show.image,
    }));
}