import { Show } from './types';

export const SHOWS: Show[] = [
  // ===== MONDAY TO SATURDAY =====

  {
    id: 1,
    title: 'The Turning Point',
    host: 'Noah Bennett',
    startTime: '00:00',
    endTime: '06:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208853/logotheturningpoint_vkfag6.png',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 2,
    title: 'Praise FM Worship',
    host: 'Praise FM Australia',
    startTime: '06:00',
    endTime: '07:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208853/logoworship_v2gdet.png',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 3,
    title: 'Aussie Morning',
    host: 'Olivia Blake',
    startTime: '07:00',
    endTime: '12:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208735/logoaussiemorning_viwgyz.png',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 4,
    title: 'Praise FM Worship',
    host: 'Praise FM Australia',
    startTime: '12:00',
    endTime: '13:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208853/logoworship_v2gdet.png',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 5,
    title: 'Midday Journey',
    host: 'Liam Carter',
    startTime: '13:00',
    endTime: '16:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208853/logomiddayjourney_g3fscw.png',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 6,
    title: 'Praise FM Non Stop',
    host: 'Praise FM Australia',
    startTime: '16:00',
    endTime: '17:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208852/logononstop_i20xbg.png',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 7,
    title: 'Next Wave',
    host: 'Sophie Mitchell',
    startTime: '17:00',
    endTime: '18:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208852/logonextwave_kcarnw.png',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 8,
    title: 'Road To Home',
    host: 'Emily Davis',
    startTime: '18:00',
    endTime: '20:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208852/logoroadtohome_qbvbt8.png',
    days: [1, 2, 3, 4, 5, 6],
  },

  // POP (Mon, Tue, Thu, Fri, Sat)
  {
    id: 9,
    title: 'Praise FM POP',
    host: 'Jordan Reyes',
    startTime: '20:00',
    endTime: '21:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208852/logopop_tiljyp.png',
    days: [1, 2, 4, 5, 6],
  },

  // LIVE SHOW (Wednesday only)
  {
    id: 10,
    title: 'Praise FM Live Show',
    host: 'Praise FM Australia',
    startTime: '20:00',
    endTime: '21:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208852/logoliveshow_k2aftt.png',
    days: [3],
  },

  {
    id: 11,
    title: 'Evening Vault',
    host: 'Jack Thompson',
    startTime: '21:00',
    endTime: '22:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208852/logoeveningvault_y2bsvk.png',
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 12,
    title: 'Praise FM Worship',
    host: 'Praise FM Australia',
    startTime: '22:00',
    endTime: '00:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208853/logoworship_v2gdet.png',
    days: [1, 2, 3, 4, 5, 6],
  },

  // ===== SUNDAY =====

  {
    id: 13,
    title: 'The Turning Point',
    host: 'Noah Bennett',
    startTime: '00:00',
    endTime: '06:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208853/logotheturningpoint_vkfag6.png',
    days: [0],
  },
  {
    id: 14,
    title: 'Praise FM Worship',
    host: 'Praise FM Australia',
    startTime: '06:00',
    endTime: '07:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208853/logoworship_v2gdet.png',
    days: [0],
  },
  {
    id: 15,
    title: 'Road to Church',
    host: 'Matthew Reed',
    startTime: '07:00',
    endTime: '12:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208851/logoroadtochurch_vxtrwl.png',
    days: [0],
  },
  {
    id: 16,
    title: 'Praise FM Worship',
    host: 'Praise FM Australia',
    startTime: '12:00',
    endTime: '13:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208853/logoworship_v2gdet.png',
    days: [0],
  },
  {
    id: 17,
    title: 'Midday Journey',
    host: 'Liam Carter',
    startTime: '13:00',
    endTime: '16:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208853/logomiddayjourney_g3fscw.png',
    days: [0],
  },
  {
    id: 18,
    title: 'Praise FM Non Stop',
    host: 'Praise FM Australia',
    startTime: '16:00',
    endTime: '17:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208852/logononstop_i20xbg.png',
    days: [0],
  },
  {
    id: 19,
    title: 'Next Wave',
    host: 'Sophie Mitchell',
    startTime: '17:00',
    endTime: '18:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208852/logonextwave_kcarnw.png',
    days: [0],
  },
  {
    id: 20,
    title: 'Praise FM Worship',
    host: 'Praise FM Australia',
    startTime: '18:00',
    endTime: '20:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208853/logoworship_v2gdet.png',
    days: [0],
  },
  {
    id: 21,
    title: 'Praise FM POP',
    host: 'Jordan Reyes',
    startTime: '20:00',
    endTime: '21:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208852/logopop_tiljyp.png',
    days: [0],
  },
  {
    id: 22,
    title: 'Evening Vault',
    host: 'Jack Thompson',
    startTime: '21:00',
    endTime: '22:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208852/logoeveningvault_y2bsvk.png',
    days: [0],
  },
  {
    id: 23,
    title: 'Sunday Message',
    host: 'Pastoral Team',
    startTime: '22:00',
    endTime: '22:30',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208852/logosundaymessage_zuqwhu.png',
    days: [0],
  },
  {
    id: 24,
    title: 'Praise FM Worship',
    host: 'Praise FM Australia',
    startTime: '22:30',
    endTime: '00:00',
    image: 'https://res.cloudinary.com/ddhu86ukg/image/upload/v1774208853/logoworship_v2gdet.png',
    days: [0],
  },
];